"""Export a trained LensSoilNet for the microcontroller.

    python -m lens_soiling.export runs/soilnet/soilnet.pt --out runs/soilnet

Produces:
  soilnet_fp32.onnx      -- BatchNorm folded, opset 13.  Feed this to
                            STM32Cube.AI (X-CUBE-AI) directly, or convert
                            with `onnx2tf` -> full-int8 .tflite for TFLM.
  soilnet_int8.pt        -- PyTorch eager static-quantized model (qnnpack),
                            for checking int8 accuracy on the PC.
  soilnet_int8_weights.h -- C header with int8 weights + scales/zero-points
                            per layer, for a hand-written CMSIS-NN path.
  export_report.json     -- sizes and fp32 vs int8 agreement on calibration tiles.
"""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path

import numpy as np
import torch
from torch import nn
from torch.ao.quantization import (
    QConfig, HistogramObserver, PerChannelMinMaxObserver, prepare, convert, QuantStub, DeQuantStub,
)
from torch.utils.data import DataLoader

from .dataset import SyntheticTiles, load_backgrounds
from .model import LensSoilNet


class QuantWrapper(nn.Module):
    def __init__(self, m: nn.Module):
        super().__init__()
        self.quant, self.m, self.dequant = QuantStub(), m, DeQuantStub()

    def forward(self, x):
        return self.dequant(self.m(self.quant(x)))


def fold_bn(model: LensSoilNet) -> LensSoilNet:
    """Fuse Conv+BN(+ReLU6) in place so exported graphs have no BatchNorm."""
    model = copy.deepcopy(model).eval()
    for mod in model.modules():
        if isinstance(mod, nn.Sequential) and len(mod) == 3 and isinstance(mod[1], nn.BatchNorm2d):
            torch.ao.quantization.fuse_modules(mod, ["0", "1", "2"], inplace=True)
    return model


def quantize_int8(model: LensSoilNet, calib: DataLoader) -> nn.Module:
    torch.backends.quantized.engine = "qnnpack"
    q = QuantWrapper(fold_bn(model))
    # per-channel symmetric weights (what TFLM / CMSIS-NN expect), per-tensor
    # affine uint8 activations with a histogram observer for tighter ranges.
    q.qconfig = QConfig(
        activation=HistogramObserver.with_args(reduce_range=False),
        weight=PerChannelMinMaxObserver.with_args(dtype=torch.qint8, qscheme=torch.per_channel_symmetric),
    )
    prepare(q, inplace=True)
    with torch.no_grad():
        for x, _ in calib:
            q(x)
    return convert(q, inplace=True)


def write_c_header(qmodel: nn.Module, path: Path) -> int:
    """Dump every quantized conv/linear weight as int8 arrays. Returns bytes."""
    lines = ["/* generated by lens_soiling.export -- int8 weights for LensSoilNet */", "#include <stdint.h>", ""]
    total = 0
    for name, mod in qmodel.named_modules():
        w = getattr(mod, "weight", None)
        if not callable(w):
            continue
        wq = w()
        if not wq.is_quantized:
            continue
        ints = wq.int_repr().numpy().astype(np.int8).ravel()
        total += ints.size
        cname = name.replace(".", "_")
        if wq.qscheme() in (torch.per_channel_affine, torch.per_channel_symmetric):
            scales = wq.q_per_channel_scales().numpy()
            zps = wq.q_per_channel_zero_points().numpy()
        else:
            scales, zps = np.array([wq.q_scale()]), np.array([wq.q_zero_point()])
        lines.append(f"/* {name}: shape {tuple(wq.shape)} */")
        lines.append(f"static const int8_t {cname}_w[{ints.size}] = {{" + ",".join(map(str, ints.tolist())) + "};")
        lines.append(f"static const float {cname}_scale[{scales.size}] = {{" + ",".join(f"{s:.8g}f" for s in scales) + "};")
        lines.append(f"static const int32_t {cname}_zp[{zps.size}] = {{" + ",".join(map(str, zps.astype(int).tolist())) + "};")
        lines.append("")
    path.write_text("\n".join(lines))
    return total


def export(weights: Path, out: Path, backgrounds: str | None = None, width: float = 1.0, n_calib: int = 256) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    model = LensSoilNet(width=width)
    model.load_state_dict(torch.load(weights, map_location="cpu"))
    model.eval()
    folded = fold_bn(model)

    calib_ds = SyntheticTiles(load_backgrounds(backgrounds) or None, n_calib, seed=99, augment=False)
    calib = DataLoader(calib_ds, batch_size=32)

    report: dict = {"weights": str(weights)}
    dummy = torch.zeros(1, 3, 64, 64)
    onnx_path = out / "soilnet_fp32.onnx"
    try:
        torch.onnx.export(folded, dummy, str(onnx_path), opset_version=13, input_names=["tile"],
                          output_names=["logits"], dynamic_axes={"tile": {0: "n"}, "logits": {0: "n"}})
        report["onnx_bytes"] = onnx_path.stat().st_size
    except Exception as e:  # onnx package missing on this machine
        report["onnx_error"] = f"{type(e).__name__}: {e}"

    qmodel = quantize_int8(model, calib)
    torch.save(qmodel.state_dict(), out / "soilnet_int8.pt")
    report["int8_weight_bytes"] = write_c_header(qmodel, out / "soilnet_int8_weights.h")
    report["fp32_param_bytes"] = sum(p.numel() for p in model.parameters()) * 4

    agree, n, drift = 0, 0, 0.0
    with torch.no_grad():
        for x, _ in calib:
            a, b = folded(x), qmodel(x)
            agree += int((a.argmax(1) == b.argmax(1)).sum())
            drift += float((a.softmax(1) - b.softmax(1)).abs().max(1).values.sum())
            n += len(x)
    report["int8_vs_fp32_argmax_agreement"] = agree / n
    report["int8_vs_fp32_mean_max_prob_drift"] = drift / n
    (out / "export_report.json").write_text(json.dumps(report, indent=2))
    return report


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("weights")
    ap.add_argument("--out", default="runs/soilnet")
    ap.add_argument("--backgrounds", default=None)
    ap.add_argument("--width", type=float, default=1.0)
    a = ap.parse_args()
    print(json.dumps(export(Path(a.weights), Path(a.out), a.backgrounds, a.width), indent=2))


if __name__ == "__main__":
    main()
