"""Convert a Keras model to full-integer int8 TFLite and a C array for TFLM.

    python -m pretrained.to_tflite runs/student/student.keras data/patches/val \
        --out runs/student --name soil_student

Writes:
  <name>_fp32.tflite     reference
  <name>_int8.tflite     full-integer: int8 weights, int8 activations, int8 I/O
  <name>_int8.cc/.h      `alignas(16) const unsigned char g_<name>[]` + length
  tflite_report.json     sizes, op list, int8-vs-fp32 agreement on the patches

Full-integer quantization needs a *representative dataset*: a few hundred
real inputs the converter runs through the fp32 graph to record activation
ranges per tensor.  Using val patches (not train) avoids tuning the ranges
on the same images the weights were fitted to.

Input scale/zero-point are read from the .tflite and printed; the firmware
must apply the same mapping (see tflm/soil_inference.cc).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

try:
    import tensorflow as tf
    from tensorflow import keras
except ImportError as e:  # pragma: no cover
    raise SystemExit("pip install tensorflow") from e

from .port_breckon import lrn  # noqa: F401


def load_patches(folder: Path, side: int, limit: int) -> np.ndarray:
    from PIL import Image

    files = sorted(p for p in folder.rglob("*") if p.suffix.lower() in {".png", ".jpg", ".jpeg"})[:limit]
    if not files:
        raise SystemExit(f"no images under {folder}")
    arr = [np.asarray(Image.open(p).convert("RGB").resize((side, side), Image.LANCZOS), dtype=np.float32) / 255.0 for p in files]
    return np.stack(arr)


def convert(model: keras.Model, rep: np.ndarray, int8: bool) -> bytes:
    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    if int8:
        conv.optimizations = [tf.lite.Optimize.DEFAULT]
        conv.representative_dataset = lambda: (([x[None]],) for x in rep)
        conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        conv.inference_input_type = tf.int8
        conv.inference_output_type = tf.int8
    return conv.convert()


def run_tflite(model_bytes: bytes, x: np.ndarray) -> np.ndarray:
    it = tf.lite.Interpreter(model_content=model_bytes)
    it.allocate_tensors()
    inp, out = it.get_input_details()[0], it.get_output_details()[0]
    preds = []
    for xi in x:
        xi = xi[None].astype(np.float32)
        if inp["dtype"] == np.int8:
            s, z = inp["quantization"]
            xi = np.clip(np.round(xi / s + z), -128, 127).astype(np.int8)
        it.set_tensor(inp["index"], xi)
        it.invoke()
        y = it.get_tensor(out["index"])[0]
        if out["dtype"] == np.int8:
            s, z = out["quantization"]
            y = (y.astype(np.float32) - z) * s
        preds.append(y)
    return np.stack(preds)


def op_list(model_bytes: bytes) -> list[str]:
    it = tf.lite.Interpreter(model_content=model_bytes)
    return sorted({d["op_name"] for d in it._get_ops_details()})  # noqa: SLF001


def write_c_array(model_bytes: bytes, out: Path, name: str) -> None:
    sym = f"g_{name}"
    body = ",".join(f"0x{b:02x}" for b in model_bytes)
    lines = [f"// Auto-generated by pretrained.to_tflite from {name}_int8.tflite", "#include <cstdint>", "",
             f"alignas(16) const unsigned char {sym}[] = {{{body}}};",
             f"const unsigned int {sym}_len = {len(model_bytes)};", ""]
    (out / f"{name}_int8.cc").write_text("\n".join(lines))
    (out / f"{name}_int8.h").write_text(
        f"#pragma once\nextern const unsigned char {sym}[];\nextern const unsigned int {sym}_len;\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("model")
    ap.add_argument("rep_folder", help="folder of representative patches (use val/)")
    ap.add_argument("--out", default="runs/tflite")
    ap.add_argument("--name", default="soil_student")
    ap.add_argument("--n-rep", type=int, default=300)
    a = ap.parse_args()

    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    model = keras.models.load_model(a.model, custom_objects={"lrn": lrn}, safe_mode=False)
    side = model.input_shape[1]
    rep = load_patches(Path(a.rep_folder), side, a.n_rep)

    fp32 = convert(model, rep, int8=False)
    q8 = convert(model, rep, int8=True)
    (out / f"{a.name}_fp32.tflite").write_bytes(fp32)
    (out / f"{a.name}_int8.tflite").write_bytes(q8)
    write_c_array(q8, out, a.name)

    ref, quant = run_tflite(fp32, rep), run_tflite(q8, rep)
    it = tf.lite.Interpreter(model_content=q8)
    inp = it.get_input_details()[0]
    report = {
        "fp32_bytes": len(fp32), "int8_bytes": len(q8), "ops": op_list(q8),
        "input_quant_scale_zero": [float(inp["quantization"][0]), int(inp["quantization"][1])],
        "argmax_agreement_int8_vs_fp32": float((ref.argmax(1) == quant.argmax(1)).mean()),
        "keras_params": int(model.count_params()),
    }
    (out / "tflite_report.json").write_text(json.dumps(report, indent=2))
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
