// OV7670 over DCMI + DMA2, QQVGA RGB565 -> RGB888.
//
// Wiring (Nucleo-F4 with DCMI-capable part, e.g. F446/F407):
//   DCMI  D0..D7, PCLK, HSYNC, VSYNC  -> OV7670 D0..D7, PCLK, HREF, VSYNC
//   I2C1  SCL/SDA                     -> OV7670 SIOC/SIOD  (SCCB, addr 0x42)
//   TIM   MCO / PWM 12-24 MHz         -> OV7670 XCLK
// `hdcmi`, `hdma_dcmi`, `hi2c1` are generated by CubeMX from Final.ioc once
// DCMI and I2C1 are enabled there.

#include "camera_dcmi.h"

#include <string.h>

#include "stm32f4xx_hal.h"

extern DCMI_HandleTypeDef hdcmi;
extern I2C_HandleTypeDef hi2c1;

#define OV7670_ADDR 0x42

// Raw RGB565 frame written by DMA.  32-bit aligned for the DMA word transfers.
static uint16_t s_frame565[CAM_W * CAM_H] __attribute__((aligned(4)));
static volatile int s_frame_done;

// Minimal OV7670 register set: reset, QQVGA, RGB565, PCLK from XCLK,
// auto white balance / exposure on.  Values from the OV7670 datasheet and
// the common Linux ov7670.c init tables.
static const uint8_t k_ov7670_init[][2] = {
    {0x12, 0x80},  // COM7  reset
    {0x12, 0x14},  // COM7  QVGA + RGB
    {0x40, 0xD0},  // COM15 RGB565, full range
    {0x11, 0x01},  // CLKRC prescale /2
    {0x0C, 0x04},  // COM3  enable scaling (downsample to QQVGA)
    {0x3E, 0x1A},  // COM14 PCLK divider /4 + manual scaling
    {0x70, 0x3A},  // SCALING_XSC
    {0x71, 0x35},  // SCALING_YSC
    {0x72, 0x22},  // SCALING_DCWCTR  /4 both axes -> 160x120
    {0x73, 0xF2},  // SCALING_PCLK_DIV
    {0xA2, 0x02},  // SCALING_PCLK_DELAY
    {0x13, 0xE7},  // COM8  AGC, AWB, AEC on
    {0x3A, 0x04},  // TSLB  UYVY order
    {0x15, 0x00},  // COM10 VSYNC/HREF polarities default
};

static int sccb_write(uint8_t reg, uint8_t val) {
  uint8_t buf[2] = {reg, val};
  return HAL_I2C_Master_Transmit(&hi2c1, OV7670_ADDR, buf, 2, 100) == HAL_OK;
}

int CameraInit(void) {
  for (unsigned i = 0; i < sizeof(k_ov7670_init) / sizeof(k_ov7670_init[0]); ++i) {
    if (!sccb_write(k_ov7670_init[i][0], k_ov7670_init[i][1])) return 0;
    if (i == 0) HAL_Delay(5);  // settle after reset
  }
  return 1;
}

// DCMI frame-complete callback (HAL calls this from the DMA/DCMI IRQ).
void HAL_DCMI_FrameEventCallback(DCMI_HandleTypeDef* h) {
  (void)h;
  s_frame_done = 1;
}

int CameraCaptureRGB888(uint8_t* rgb888) {
  s_frame_done = 0;
  // Snapshot mode: one frame then DCMI stops.  Length is in 32-bit words.
  if (HAL_DCMI_Start_DMA(&hdcmi, DCMI_MODE_SNAPSHOT, (uint32_t)s_frame565, (CAM_W * CAM_H * 2) / 4) != HAL_OK)
    return 0;
  const uint32_t t0 = HAL_GetTick();
  while (!s_frame_done) {
    if (HAL_GetTick() - t0 > 500) {  // no VSYNC in 0.5 s: camera unplugged
      HAL_DCMI_Stop(&hdcmi);
      return 0;
    }
  }
  HAL_DCMI_Stop(&hdcmi);

  // RGB565 -> RGB888, replicating the high bits into the low bits so full
  // white maps to 255, not 248.
  for (int i = 0; i < CAM_W * CAM_H; ++i) {
    const uint16_t p = s_frame565[i];
    const uint8_t r5 = (p >> 11) & 0x1F, g6 = (p >> 5) & 0x3F, b5 = p & 0x1F;
    rgb888[3 * i + 0] = (uint8_t)((r5 << 3) | (r5 >> 2));
    rgb888[3 * i + 1] = (uint8_t)((g6 << 2) | (g6 >> 4));
    rgb888[3 * i + 2] = (uint8_t)((b5 << 3) | (b5 >> 2));
  }
  return 1;
}
