/* Weather-Resistant Camera: on-chip rain detection main loop.
 *
 * This is ../../../main.c with the PC removed from the loop.  The heater and
 * servo code is unchanged.  The wiper trigger now comes from the int8
 * raindrop CNN running under TensorFlow Lite Micro on the STM32 instead of a
 * "START" byte string over UART.
 *
 * Per loop iteration (about 4 s when idle, dominated by the capture cadence):
 *   1. read on-die temperature, switch heater MOSFET on PA5 below THRESH_C
 *   2. capture a 160x120 RGB frame over DCMI
 *   3. classify the 3x2 grid of 48 px tiles  -> coverage in [0,1]
 *   4. if coverage >= WIPE_THRESHOLD and temperature > 0 C and the cooldown
 *      has elapsed, sweep the servo 60 -> 115 -> 60 degrees
 *   5. print a one-line status over USART2 for logging on the PC
 *
 * CubeMX (Final.ioc) must have: TIM2 CH1 PWM (servo), ADC1 temp sensor,
 * USART2, DCMI + DMA2 stream, I2C1, plus a 12-24 MHz clock out for XCLK.
 */

#include <stdio.h>
#include <string.h>

#include "main.h"
#include "camera_dcmi.h"
#include "raindrop_inference.h"

/* ---- peripherals generated by CubeMX (declared in main.h / main.c) ---- */
extern ADC_HandleTypeDef hadc1;
extern TIM_HandleTypeDef htim2;
extern UART_HandleTypeDef huart2;
extern void SystemClock_Config(void);
extern void MX_GPIO_Init(void);
extern void MX_ADC1_Init(void);
extern void MX_USART2_UART_Init(void);
extern void MX_TIM2_Init(void);
extern void MX_DCMI_Init(void);
extern void MX_I2C1_Init(void);
extern void MX_DMA_Init(void);

/* ---- tunables ---- */
#define HEATER_THRESH_C   20.5f   /* demo threshold; 0-2 C in the field */
#define WIPE_THRESHOLD    0.05f   /* same 5 % rule as the OpenCV heuristic */
#define WIPE_COOLDOWN_MS  4000u   /* one sweep is ~3.7 s at 100 ms/step */
#define LOOP_PERIOD_MS    1000u

/* ---- factory temperature calibration (STM32F4 reference manual) ---- */
#define TS_CAL1 (*((uint16_t*)0x1FFF7A2C))  /* raw ADC at 30 C  */
#define TS_CAL2 (*((uint16_t*)0x1FFF7A2E))  /* raw ADC at 110 C */

static uint8_t s_frame[CAM_W * CAM_H * 3];
static uint8_t s_grid[(CAM_H / RAINDROP_TILE) * (CAM_W / RAINDROP_TILE)];

int _write(int file, char* ptr, int len) {
  (void)file;
  HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
  return len;
}

void Set_Servo_Angle(TIM_HandleTypeDef* htim, uint32_t channel, uint8_t angle) {
  uint32_t pulse = 210 + (angle * (1050 - 210) / 180);
  __HAL_TIM_SET_COMPARE(htim, channel, pulse);
}

static float ReadTemperatureC(void) {
  HAL_ADC_Start(&hadc1);
  HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
  uint32_t raw = HAL_ADC_GetValue(&hadc1);
  HAL_ADC_Stop(&hadc1);
  float t = ((float)raw - TS_CAL1) * (110.0f - 30.0f) / ((float)TS_CAL2 - TS_CAL1) + 30.0f;
  return t - 9.0f; /* manual offset found in testing, as in main.c */
}

static void Wipe(void) {
  for (uint8_t a = 60; a <= 115; a += 3) { Set_Servo_Angle(&htim2, TIM_CHANNEL_1, a); HAL_Delay(100); }
  for (uint8_t a = 115; a > 60; a -= 3)  { Set_Servo_Angle(&htim2, TIM_CHANNEL_1, a); HAL_Delay(100); }
}

int main(void) {
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_ADC1_Init();
  MX_USART2_UART_Init();
  MX_TIM2_Init();
  MX_I2C1_Init();
  MX_DCMI_Init();
  HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);
  Set_Servo_Angle(&htim2, TIM_CHANNEL_1, 60);

  const int cam_ok = CameraInit();
  const int nn_ok = RaindropInit();
  printf("camera=%d model=%d\r\n", cam_ok, nn_ok);

  uint32_t last_wipe = 0;
  for (;;) {
    const uint32_t t0 = HAL_GetTick();

    /* 1. heater from the thermistor, unchanged */
    const float temp_c = ReadTemperatureC();
    const int heat = temp_c < HEATER_THRESH_C;
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, heat ? GPIO_PIN_RESET : GPIO_PIN_SET);

    /* 2-3. capture and classify */
    float cover = -1.0f;
    if (cam_ok && nn_ok && CameraCaptureRGB888(s_frame)) {
      cover = RaindropCoverage(s_frame, CAM_W, CAM_H, s_grid);
    }

    /* 4. wipe on coverage; never run the wiper on ice */
    int wiped = 0;
    if (cover >= WIPE_THRESHOLD && temp_c > 0.0f && (HAL_GetTick() - last_wipe) > WIPE_COOLDOWN_MS) {
      Wipe();
      last_wipe = HAL_GetTick();
      wiped = 1;
    }

    /* 5. status line: temperature, heater, coverage, grid, inference time */
    printf("T=%.1fC heat=%d cover=%.2f grid=", temp_c, heat, cover);
    for (unsigned i = 0; i < sizeof s_grid; ++i) printf("%d", s_grid[i]);
    printf(" nn_us=%lu wipe=%d\r\n", (unsigned long)RaindropLastInferenceUs(), wiped);

    const uint32_t spent = HAL_GetTick() - t0;
    if (spent < LOOP_PERIOD_MS) HAL_Delay(LOOP_PERIOD_MS - spent);
  }
}
